[package]
name = "fruitmachine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm="0.23.2"
rusty_time="0.11.3"
rusty_audio="1.2.1"
crossbeam="0.8.1"
random-number="0.1.7"